name: 'ethio_medical_data_warehouse'
version: '1.0.0'
config-version: 2

profile: 'ethio_medical_data_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "dbt_modules"

require-dbt-version: ">=1.0.0"